/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Evaluacion;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorAsignatura;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorEvaluacion;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorRegistrarCurso;
import co.edu.eam.ingesoft.desarrollo.logica.excepciones.ExcepcionNegocio;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCalificacion extends javax.swing.JInternalFrame implements ActionListener {

	private ControladorAdministradorAsignatura conAsignatura;
	private ControladorAdministradorEvaluacion conEvaluacion;
	private ControladorAdministradorCurso conCurso;

	/**
	 * Creates new form VentanaCrearCalificacion
	 */
	public VentanaCrearCalificacion() {
		initComponents();
		conAsignatura = new ControladorAdministradorAsignatura();
		conEvaluacion = new ControladorAdministradorEvaluacion();
		conCurso = new ControladorAdministradorCurso();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		CBCursoDatosAsignatura = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCalificaciones = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		tfnombrecal = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfnombrepor = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		tfporcentajenoasignado = new javax.swing.JTextField();
		jBCalificacionCursoCrear = new javax.swing.JButton();
		btnQuitarCalificacion = new javax.swing.JButton();

		setTitle("Administrar Calificaciones Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10icono.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jLabel3.setText("Curso");

		CBCursoDatosAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CBCursoDatosAsignaturaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(37,
																37, 37)
														.addComponent(tfcodigoasignatura,
																javax.swing.GroupLayout.PREFERRED_SIZE, 231,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel3))
														.addGap(33, 33, 33)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(tfnombreasignatura)
																.addComponent(CBCursoDatosAsignatura, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(CBCursoDatosAsignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(29, Short.MAX_VALUE)));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); // NOI18N

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones Curso"));

		tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Nombre", "Porcentaje" }));
		jScrollPane1.setViewportView(tablaCalificaciones);

		jLabel5.setText("Nombre");

		jLabel6.setText("Porcentaje");

		jLabel7.setText("No Asignado");

		tfporcentajenoasignado.setEditable(false);
		tfporcentajenoasignado.setToolTipText("Porcentaje faltante por asignar");

		jBCalificacionCursoCrear
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		jBCalificacionCursoCrear.setToolTipText("Agregar Calificacion");
		jBCalificacionCursoCrear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBCalificacionCursoCrearActionPerformed(evt);
			}
		});

		btnQuitarCalificacion
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
		btnQuitarCalificacion.setToolTipText("Quitar Calificacion Seleccionada");
		btnQuitarCalificacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitarCalificacionActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
						.createSequentialGroup()
						.addContainerGap().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
										.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5).addComponent(jLabel6)
												.addComponent(jLabel7))
										.addGap(21, 21, 21)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(tfporcentajenoasignado,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 247,
																Short.MAX_VALUE)
														.addComponent(tfnombrepor,
																javax.swing.GroupLayout.Alignment.LEADING))
												.addComponent(tfnombrecal, javax.swing.GroupLayout.PREFERRED_SIZE, 247,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jBCalificacionCursoCrear))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnQuitarCalificacion))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel2Layout
										.createSequentialGroup().addGap(26, 26, 26)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(tfnombrecal,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel6).addComponent(tfnombrepor,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addGap(1, 1, 1).addComponent(jBCalificacionCursoCrear,
																javax.swing.GroupLayout.DEFAULT_SIZE, 49,
																Short.MAX_VALUE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7).addComponent(tfporcentajenoasignado,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnQuitarCalificacion).addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
								.addGap(34, 34, 34).addComponent(jLabel4).addGap(18, 18, 18).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(0, 18, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void CBCursoDatosAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CBCursoDatosAsignaturaActionPerformed

		try {
			String codigo = (String) CBCursoDatosAsignatura.getSelectedItem();

			List<Evaluacion> obtenerPo = conEvaluacion.listEvaluacion(codigo);

			DefaultTableModel df = (DefaultTableModel) tablaCalificaciones.getModel();
			df.setRowCount(0);

			for (int i = 0; i < obtenerPo.size(); i++) {

				df.addRow(new Object[] { obtenerPo.get(i).getNombre(), obtenerPo.get(i).getPorcentaje() });

			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_CBCursoDatosAsignaturaActionPerformed

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
		try {
			String cod = tfcodigoasignatura.getText();
			Asignatura cust = conAsignatura.buscar(cod);
			List<Curso> cursos = conEvaluacion.listarCurso(cod);
			if (cust != null) {
					for (int i = 0; i < cursos.size(); i++) {
						tfnombreasignatura.setText(cust.getNombre());
					CBCursoDatosAsignatura.addItem(cursos.get(i).getCodigo());
				}

			} else {
				JOptionPane.showMessageDialog(null, "La asignatura no se encuetra registrado");
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

		}

	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void btnQuitarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarCalificacionActionPerformed
		
		try {
			String codigo = (String) CBCursoDatosAsignatura.getSelectedItem();

			int fila = this.tablaCalificaciones.getSelectedRow();
			String nombreEval = String.valueOf(tablaCalificaciones.getValueAt(fila, 0));
			
			conEvaluacion.eliminarEvaluaciones(codigo, nombreEval);
			
			JOptionPane.showMessageDialog(null, "Eliminacion exitosa");

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showConfirmDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		
	}// GEN-LAST:event_btnQuitarCalificacionActionPerformed

	private void jBCalificacionCursoCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCalificacionCursoCrearActionPerformed
		try {
			Evaluacion evaluacion = new Evaluacion();

			String codigo = (String) CBCursoDatosAsignatura.getSelectedItem();
			Curso cur = conCurso.buscar(codigo);

			evaluacion.setCodigo(cur);
			evaluacion.setNombre(tfnombrecal.getText());

			double porcentaje = Double.parseDouble(tfnombrepor.getText());

			evaluacion.setPorcentaje(porcentaje);

			String porFaltante = String.valueOf(conEvaluacion.porcentaje(evaluacion.getCodigo().getCodigo(), porcentaje));

			tfporcentajenoasignado.setText(porFaltante);

			conEvaluacion.crearCalificaciones(evaluacion);

			JOptionPane.showMessageDialog(null, "Evaluacion creada");
		} catch (ExcepcionNegocio exN) {
			JOptionPane.showMessageDialog(null, exN.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_jBCalificacionCursoCrearActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox CBCursoDatosAsignatura;
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnQuitarCalificacion;
	private javax.swing.JButton jBCalificacionCursoCrear;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaCalificaciones;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombrecal;
	private javax.swing.JTextField tfnombrepor;
	private javax.swing.JTextField tfporcentajenoasignado;

	// End of variables declaration//GEN-END:variables
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub

	}
}
