/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.persistencia.dao.definiciones.IAsignaturaDAO;
import co.edu.eam.disenosoft.universidad.persistencia.dao.definiciones.IEstudianteDAO;
import co.edu.eam.disenosoft.universidad.persistencia.dao.implementacion.jpa.DAOAsignaturaJPA;
import co.edu.eam.disenosoft.universidad.persistencia.dao.implementacion.jpa.DAOEstudianteJPA;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.Estudiante;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.RegistroCurso;
import co.edu.eam.disenosoft.universidad.persistencia.modelo.entidades.SesionCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorAsignatura;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorEstudiante;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministradorRegistrarCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorAdministrarDocente;
import co.edu.eam.ingesoft.desarrollo.logica.excepciones.ExcepcionNegocio;

/**
 *
 * @author dir_software
 */
public class VentanaRegistrarCurso extends javax.swing.JInternalFrame implements ActionListener {

	private ControladorAdministradorRegistrarCurso conRegistrarCurso;
	private ControladorAdministradorEstudiante conEs;
	private ControladorAdministradorAsignatura conAsignatura;

	/**
	 * Creates new form VentanaRegistrarCurso
	 */
	public VentanaRegistrarCurso() {
		initComponents();
		conRegistrarCurso = new ControladorAdministradorRegistrarCurso();
		conAsignatura = new ControladorAdministradorAsignatura();
		conEs = new ControladorAdministradorEstudiante();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaHorario = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		tfcreditosasignatura = new javax.swing.JTextField();
		btnRegistrarCurso = new javax.swing.JButton();
		btnQuitarAsignatura = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		tfTipoAsignatura = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfcedulaestudiante = new javax.swing.JTextField();
		btnBuscarEstuainte = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		tfnombreestudiante = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfcreditosregistradosestudiante = new javax.swing.JTextField();

		setIconifiable(true);
		setTitle("Registrar Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abc1.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Asignatura"));

		tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Codigo", "Horario" }));
		jScrollPane1.setViewportView(tablaHorario);

		jLabel5.setText("Creditos");

		tfcreditosasignatura.setEditable(false);

		btnRegistrarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegistrarCursoActionPerformed(evt);
			}
		});

		btnQuitarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
		btnQuitarAsignatura.setToolTipText("Quitar Asignatura Registrada");
		btnQuitarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitarAsignaturaActionPerformed(evt);
			}
		});

		jLabel7.setText("Tipo:");

		tfTipoAsignatura.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout
														.createSequentialGroup().addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel2)
																		.addComponent(
																				jLabel1)
																		.addComponent(jLabel5))
														.addGap(25, 25, 25)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(tfcreditosasignatura,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				58,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jLabel7).addGap(18, 18, 18)
																		.addComponent(tfTipoAsignatura))
																.addComponent(tfnombreasignatura,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 259,
																		Short.MAX_VALUE)
																.addComponent(tfcodigoasignatura))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(btnBuscarAsignatura))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(btnRegistrarCurso).addGap(18, 18, 18)
														.addComponent(btnQuitarAsignatura)))
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel1).addComponent(tfcodigoasignatura,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel2).addComponent(tfnombreasignatura,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5)
								.addComponent(tfcreditosasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7)
								.addComponent(tfTipoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnRegistrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnQuitarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante"));

		jLabel3.setText("Cedula");

		btnBuscarEstuainte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarEstuainte.setToolTipText("Buscar Docente");
		btnBuscarEstuainte.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarEstuainteActionPerformed(evt);
			}
		});

		jLabel4.setText("Nombre");

		tfnombreestudiante.setEditable(false);

		jLabel6.setText("Creditos Registrados");

		tfcreditosregistradosestudiante.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6).addComponent(jLabel4).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfcedulaestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 259,
										Short.MAX_VALUE)
								.addComponent(tfnombreestudiante).addComponent(tfcreditosregistradosestudiante))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(tfcedulaestudiante,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(5, 5, 5)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(tfnombreestudiante,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(tfcreditosregistradosestudiante,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
										jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(15, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarCursoActionPerformed
		try {

			int credito = Integer.parseInt(tfcreditosasignatura.getText());

			RegistroCurso reg = new RegistroCurso();

			// if(tablaHorario.getSelectedColumn() != 0 &&
			// tablaHorario.getSelectedColumn() != -1
			// ){
			int fila = this.tablaHorario.getSelectedRow();
			int cod = Integer.parseInt(String.valueOf(tablaHorario.getValueAt(fila, 0)));

			String codigo = String.valueOf(cod);

			Curso cur = conRegistrarCurso.buscarCurso(codigo);
			String estCed = tfcedulaestudiante.getText();
			Estudiante est = conRegistrarCurso.buscarEst(estCed);

			reg.setCurso(cur);
			reg.setEstudiante(est);

			conRegistrarCurso.registrarCurso(reg, est, credito);
			;
			JOptionPane.showMessageDialog(null, "Registro");
			// }else{
			// JOptionPane.showMessageDialog(null, "Seleccione una opcion en la
			// tabla");
			// }
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnRegistrarCursoActionPerformed

	private void btnBuscarEstuainteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarEstuainteActionPerformed
		// TODO add your handling code here:

		try {

			String codEstudiante = tfcedulaestudiante.getText();
			Estudiante cust = conEs.buscarEstudiante(codEstudiante);

			if (cust != null) {
				int creditos = conRegistrarCurso.totalCreditos(cust);
				tfnombreestudiante.setText(cust.getNombre());
				tfcreditosregistradosestudiante.setText(creditos + "");
			} else {
				JOptionPane.showMessageDialog(null, "El estudiante no esta registrado");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnBuscarEstuainteActionPerformed

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignaturaActionPerformed

		try {

			String asi = tfcodigoasignatura.getText();
			Asignatura a = conAsignatura.buscar(asi);

			if (asi != null) {
				tfnombreasignatura.setText(a.getNombre());
				tfcreditosasignatura.setText(a.getNumeroCreditos() + "");
				tfTipoAsignatura.setText(a.getTipo() + "");

				DefaultTableModel df = (DefaultTableModel) tablaHorario.getModel();
				df.setRowCount(0);

				List<Curso> cursos = conRegistrarCurso.listCursosAsig(a);

				for (int i = 0; i < cursos.size(); i++) {
					String horario = "";
					for (int j = 0; j < cursos.get(i).getSesiones().size(); j++) {

						horario += cursos.get(i).getSesiones().get(j).getDia() + " de: "
								+ cursos.get(i).getSesiones().get(j).getHoraInicio() + " a "
								+ cursos.get(i).getSesiones().get(j).getHoraFinal();
					}
					df.addRow(new Object[] { cursos.get(i).getCodigo(), horario });
				}

			} else {
				JOptionPane.showMessageDialog(null, "la asignatura no esta registradaca");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void btnQuitarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarAsignaturaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnQuitarAsignaturaActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnBuscarEstuainte;
	private javax.swing.JButton btnQuitarAsignatura;
	private javax.swing.JButton btnRegistrarCurso;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaHorario;
	private javax.swing.JTextField tfTipoAsignatura;
	private javax.swing.JTextField tfcedulaestudiante;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfcreditosasignatura;
	private javax.swing.JTextField tfcreditosregistradosestudiante;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombreestudiante;
	// End of variables declaration//GEN-END:variables

	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub

	}

	public void llenarTabla() {
		try {

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "No hay sesiones registradas");
		}

	}

}
